welkin:
  zookeeper:
    server: 192.168.32.128:2181
spring:
  redis:
    host: 192.168.32.128
    port: 6379
    password:
    timeout: 3600
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 5000
        shutdown-timeout: 100

logging:
  level:
    root: error
    io.gitee.welkinfast.im: debug
